name: generate ascii

on:
  push:

jobs:
  buildjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List files
        run: ls

      - name: Installing cowsay 
        run: sudo apt install cowsay -y

      - name: Execute cowsay 
        run: cowsay -f dragon "Run for cover I'm dragon RERAW" >> dragon.txt

      - name: Upload dragon txt file
        uses: actions/upload-artifact@v4
        with:
          name: dragon-text-file
          path: dragon.txt

  testjob:
    needs: buildjob
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download dragon txt file
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file
          path: .

      - name: Find dragon.txt
        run: grep -i "dragon" dragon.txt

  deployjob:
    needs: [buildjob, testjob]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download dragon txt file
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file
          path: .

      - name: Show the file
        run: cat dragon.txt

      - name: List files
        run: ls
