name: generate ascii

on:
  push:

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: list liste
        run: ls
      - name: make script ex
        run: chmod +x .github/workflows/ascii-script.sh

      - name: excute script
        run: .github/workflows/ascii-script.sh
      - name: list liste
        run: ls
