name: generate ascii

on:
  push:

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: list liste
        run: ls

      - name: excute script
        run: ./ascii-script.sh 
      - name: list liste
        run: ls
